# stages:
#   - build
#   - deploy

# #BUILD
# build:
#   stage: build
#   interruptible: true
#   tags:
#     - Internal
#     - Worker
#   script:
#     - docker build . -t $CI_REGISTRY_IMAGE:latest
#     - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker push $CI_REGISTRY_IMAGE:latest

# ##################
# #DEPLOY

# deploy:
#   stage: deploy
#   interruptible: true
#   tags:
#     - Internal
#     - Manager
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker service update stack-name_service-name --with-registry-auth --image=$CI_REGISTRY_IMAGE:latest